//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibroEscuelaBasicaMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadesDB
    {
        public int idActividade { get; set; }
        public string descripcion { get; set; }
        public int idCurso { get; set; }
        public int idProfesor { get; set; }
    
        public virtual CursosDB CursosDB { get; set; }
        public virtual ProfesorDB ProfesorDB { get; set; }
    }
}
