//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibroEscuelaBasicaMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlumnoDB()
        {
            this.AnotacionesDB = new HashSet<AnotacionesDB>();
        }
    
        public int idAlumno { get; set; }
        public int rutAlumno { get; set; }
        public string nombreAlumno { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public int idApoderado { get; set; }
        public int idCurso { get; set; }
    
        public virtual ApoderadoDB ApoderadoDB { get; set; }
        public virtual CursosDB CursosDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnotacionesDB> AnotacionesDB { get; set; }
    }
}
