//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibroEscuelaBasicaMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnotacionesDB
    {
        public int idAnotaciones { get; set; }
        public int idTipo { get; set; }
        public string descripcion { get; set; }
        public int idProfesor { get; set; }
        public int idAlumno { get; set; }
    
        public virtual AlumnoDB AlumnoDB { get; set; }
        public virtual ProfesorDB ProfesorDB { get; set; }
        public virtual TipoAnotacionDB TipoAnotacionDB { get; set; }
    }
}
