//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibroEscuelaBasicaMedia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibroDBEntities : DbContext
    {
        public LibroDBEntities()
            : base("name=LibroDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActividadesDB> ActividadesDB { get; set; }
        public virtual DbSet<AlumnoDB> AlumnoDB { get; set; }
        public virtual DbSet<AnotacionesDB> AnotacionesDB { get; set; }
        public virtual DbSet<ApoderadoDB> ApoderadoDB { get; set; }
        public virtual DbSet<CursosDB> CursosDB { get; set; }
        public virtual DbSet<ProfesorDB> ProfesorDB { get; set; }
        public virtual DbSet<RolDB> RolDB { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoAnotacionDB> TipoAnotacionDB { get; set; }
        public virtual DbSet<UsuarioDB> UsuarioDB { get; set; }
    }
}
