//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibroEscuelaBasicaMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesorDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfesorDB()
        {
            this.ActividadesDB = new HashSet<ActividadesDB>();
            this.AnotacionesDB = new HashSet<AnotacionesDB>();
        }
    
        public int idProfesor { get; set; }
        public int rutProfesor { get; set; }
        public string nombreProfesor { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public int idUser { get; set; }
        public int idCurso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadesDB> ActividadesDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnotacionesDB> AnotacionesDB { get; set; }
        public virtual CursosDB CursosDB { get; set; }
        public virtual UsuarioDB UsuarioDB { get; set; }
    }
}
